services:
  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./.rabbitmq:/var/lib/rabbitmq
  postgres:
    container_name: postgres
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.postgresql:/var/lib/postgresql/data