version: "3.9"
services:
  nginx:
    build: .
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    ports:
      - "80:8085"
      - "8081:8086"
    depends_on:
      - app
    environment:
      - LABEL_STUDIO_HOST=$${LABEL_STUDIO_HOST:-}
    volumes:
      - label-studio:/label-studio/data:rw
    command: nginx

  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=$${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
    volumes:
      - label-studio:/label-studio/data:rw
    command: label-studio-uwsgi

  mlflow:
    restart: always
    image: angstorm/mlflow:2.18.0-boto-psycorg-amd64
    depends_on:
        - db
    ports:
        - "5000:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=https://storage.yandexcloud.net/
      - AWS_ACCESS_KEY_ID=${mlflow_s3_key_id}
      - AWS_SECRET_ACCESS_KEY=${mlflow_s3_key_secret}
    command: mlflow server --backend-store-uri postgresql://postgres@db:5432/mlflow --default-artifact-root s3://${mlflow_s3_bucket}/ --host 0.0.0.0

  db:
    image: pgautoupgrade/pgautoupgrade:13-alpine
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  label-studio:
  postgresql: